# Generated by Django 5.1.7 on 2025-03-24 01:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating Value (1-5)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Additional Comments')),
                ('user_name', models.CharField(max_length=255, verbose_name='User Name')),
                ('user_email', models.EmailField(max_length=254, verbose_name='User Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='solutions.solution', verbose_name='Solution')),
            ],
            options={
                'verbose_name': 'Solution Rating',
                'verbose_name_plural': 'Solution Ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('company', models.CharField(max_length=255, verbose_name='Company Name')),
                ('position', models.CharField(max_length=255, verbose_name='Job Position')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Customer Photo')),
                ('testimonial_text', models.TextField(verbose_name='Testimonial')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating (1-5 stars)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured on Homepage')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('approved', models.BooleanField(default=True, verbose_name='Approved for Display')),
                ('solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='solutions.solution', verbose_name='Related Solution')),
            ],
            options={
                'verbose_name': 'Customer Testimonial',
                'verbose_name_plural': 'Customer Testimonials',
                'ordering': ['-date_added'],
            },
        ),
    ]
